backend:
  name: git-gateway
  branch: main

media_folder: "public/images"
public_folder: "/images"

collections:
  - name: "pages_ko"
    label: "Pages (Korean)"
    folder: "content/ko"
    create: false
    extension: "md"
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "pages_en"
    label: "Pages (English)"
    folder: "content/en"
    create: false
    extension: "md"
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "pages_lo"
    label: "Pages (Lao)"
    folder: "content/lo"
    create: false
    extension: "md"
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
